### ISSUE TITLE
False positives?

### ISSUE THREAD

**Issue by rei-vilo** [wilhelmer/mkdocs-unused-files#1]
The **mkdocs-unused-files** throws many false positives.

The project contains different parts, called volumes, and each volume contains a sub-folder `img` for the pictures.

```
Project/
└── docs
    ├── img
    ├── Volume1
    │   └── img
    └── Volume2
        └── img
```

The plug-in is configured with

```
plugins:
    - unused_files:
        file_types:
        - png
        - jpg
        - svg
        - gif
        - jpeg
```

`Volume1/Chapter1.md` calls `![](img/Cat1.jpeg)` but the plug-in complains about `Volume1/img/Cat1.jpeg`.

```
INFO     -  The following files exist in the docs directory, but may be unused:
              - Volume1/img/Cat1.jpeg
```

Please find attached the minimal MkDocs project I am using to test **mkdocs-unused-files**. 

[Minimal_test_for_mkdocs-unused-files.zip](https://github.com/wilhelmer/mkdocs-unused-files/files/10236510/Minimal_test_for_mkdocs-unused-files.zip)

**Comment by wilhelmer** [comment]
First of all, thanks for testing, and thanks for the cats.

Second, as of now, `use_directory_urls` has to be set to `false` in `mkdocs.yml` for this plugin to work properly. I totally forgot to mention that, sorry. Also, I'm planning to release a version that will work regardless of the `use_directory_urls` setting.

So please try again with:

```yml
use_directory_urls: false
plugins:
    - unused_files:
        file_types:
        - png
        - jpg
        - svg
        - gif
        - jpeg
```
