### ISSUE TITLE
Strict mode fails `serve` on reload

### ISSUE THREAD

**Issue by johnthagen** [wilhelmer/mkdocs-unused-files#15]
With a configuration such as

```yaml
plugins:
  - unused_files:
      strict: true
      dir: images
```

The first time `mkdocs serve` is run, the plugin correctly bypassed

https://github.com/wilhelmer/mkdocs-unused-files/blob/74e28c649422bc3e0a02a3a4c6a90927ed48b660/mkdocs_unused_files/plugin.py#L38-L39

But if a Markdown file is changed, the plugin activates and fails the build after a reload.

```
WARNING -  The following files exist in the docs directory, but may be unused:
  -images/favicon.svg
Aborted with 1 warnings in strict mode!
```
