### ISSUE TITLE
Feature Request: Add the ability to use file glob in `excluded_files`

### ISSUE THREAD

**Issue by ebouchut** [wilhelmer/mkdocs-unused-files#8]
Hi, 

👍 First-off thank you for the useful plugin.

It would be useful to be able to exclude files using a file glob (wildcard pattern), something like `**/.DS-Store` to exclude any `.DS-Store` files in whatever folder or subfolder (whatever its depth) beneath `docs/`.

```yaml
plugins:
    - search
    - 
    - unused_files:
        excluded_files:
            - '**/.DS_Store'
```

Today I need to list exhaustively all `.DS-Store` files, like so:
```yaml
plugins:
    - search
    - unused_files:
        excluded_files:
            - gh-actions/.DS_Store
            - gh-actions/img/.DS_Store
            - build/.DS_Store
```
